#!/bin/bash
set -e

python -m bash_kernel.install

git clone https://github.com/AIDASoft/DD4hep
mkdir build_dd 
cd build_dd

pwd
conda list
#-DCMAKE_PREFIX_PATH=/srv/conda/envs/notebook/x86_64-conda-linux-gnu/sysroot/usr/include/ \
#-DFREETYPE_DIR=/srv/conda/envs/notebook/ \
#find /srv/conda/envs/notebook -name \*reetype\*h
#find /srv/conda/envs/notebook -name \*reetype\*so\*
#cat /srv/conda/envs/notebook/include/freetype2/freetype/freetype.h
find /srv/conda/envs/notebook -name libGL\*

cmake --debug-output -DCMAKE_PREFIX_PATH=/srv/conda/envs/notebook \
-DDD4HEP_RELAX_PYVER=ON -DDD4HEP_USE_GEANT4=ON -DBoost_NO_BOOST_CMAKE=ON \
-DDD4HEP_USE_LCIO=OFF -DBUILD_TESTING=ON -DROOT_DIR=$ROOTSYS \
-D CMAKE_BUILD_TYPE=Release ../DD4hep 
#> dd4hep_cmake.out 2>&1 

#cmake --debug-output -DEXPAT_INCLUDE_DIR=/srv/conda/envs/notebook/include \
#-DEXPAT_LIBRARY=/srv/conda/envs/notebook/lib/ \
#-DCMAKE_PREFIX_PATH=/srv/conda/envs/notebook:/srv/conda/envs/notebook/x86_64-conda-linux-gnu/sysroot/usr/include/ \
#-DZLIB_ROOT=/srv/conda/envs/notebook/ \
#-DDD4HEP_RELAX_PYVER=ON -DDD4HEP_USE_GEANT4=ON -DBoost_NO_BOOST_CMAKE=ON -DDD4HEP_USE_LCIO=OFF \
#-DBUILD_TESTING=ON -DROOT_DIR=$ROOTSYS -D CMAKE_BUILD_TYPE=Release ../DD4hep 
##> dd4hep_cmake.out 2>&1 
echo "t4"
#tail -1000 dd4hep_cmake.out
make -j4 > dd4hep_make.out 2>&1
echo "t5"
make install > dd4hep_install.out 2>&1
echo "t6"

# pip appears to leave behind 4GB of stuff.. lets remove it.
pip cache purge



